services:
  web:
    image: buettner123/hpwv-backend
    build:
      context: .
    ports:
      - "3117:3117"
    environment:
      - NODE_ENV=dev
    networks:
      - kafka-proxy

networks:
  kafka-proxy:
    name: kafka
